In [1]:
# ============================================================
# CELL 1 — IMPORTS & CONFIG
# ============================================================

import os
import sys
import gc
import time
import random
import warnings

import numpy as np
import pandas as pd
import torch
import lightning.pytorch as pl

from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# Repository
# ------------------------------------------------------------

REPO_PATH = r"C:\Users\Anusha\engression\engression-ts"

if REPO_PATH not in sys.path:
    sys.path.insert(0, REPO_PATH)

# ------------------------------------------------------------
# Experiment configuration
# ------------------------------------------------------------

SEED = 42

INPUT_CHUNK_LENGTH = 24
OUTPUT_CHUNK_LENGTH = 24

BATCH_SIZE = 64

# Engression training samples
NUM_SAMPLES_TRAIN = 2

# Prediction samples
NUM_SAMPLES_PRED = 100

NOISE_STD = 1.0
NOISE_TYPE = "uniform"

LEARNING_RATE = 1e-3

# 30 epochs at batch_size=64
MAX_STEPS = 109

DATASET_NAME = "solar_nips"

RESULTS_FILE = "nf_solar_results.csv"

print("Repository:", REPO_PATH)
print("Dataset:", DATASET_NAME)
print("Batch size:", BATCH_SIZE)
print("Training samples:", NUM_SAMPLES_TRAIN)
print("Prediction samples:", NUM_SAMPLES_PRED)
print("Max steps:", MAX_STEPS)

Repository: C:\Users\Anusha\engression\engression-ts
Dataset: solar_nips
Batch size: 64
Training samples: 2
Prediction samples: 100
Max steps: 109

In [2]:
# ============================================================
# CELL 2 — DETERMINISTIC SEEDS
# ============================================================

os.environ["PYTHONHASHSEED"] = str(SEED)
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

random.seed(SEED)
np.random.seed(SEED)

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

torch.use_deterministic_algorithms(
    True,
    warn_only=True
)

pl.seed_everything(SEED, workers=True)

print("Seed:", SEED)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Seed set to 42

Seed: 42
CUDA available: True
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU

In [2]:
# ============================================================
# CELL 3 — LOAD SOLAR NIPS
# ============================================================

from gluonts.dataset.repository.datasets import get_dataset
from gluonts.dataset.multivariate_grouper import MultivariateGrouper

ds = get_dataset(
    DATASET_NAME,
    regenerate=False
)

train_list = list(ds.train)
test_list = list(ds.test)

freq = ds.metadata.freq

num_test_dates = len(test_list) // len(train_list)

target_dim = int(
    ds.metadata.feat_static_cat[0].cardinality
)

print("Dataset:", DATASET_NAME)
print("Training series:", len(train_list))
print("Target dimensions:", target_dim)
print("Test windows:", num_test_dates)
print("Frequency:", freq)

Dataset: solar_nips
Training series: 137
Target dimensions: 137
Test windows: 7
Frequency: h

In [3]:
# ============================================================
# CELL 4 — GLUONTS → DARTS
# ============================================================

def gluonts_item_to_darts_mv(item, freq):

    start = (
        item["start"].to_timestamp()
        if hasattr(item["start"], "to_timestamp")
        else pd.Timestamp(item["start"])
    )

    target = np.asarray(item["target"])

    if target.ndim != 2:
        raise ValueError(
            f"Expected multivariate target, got {target.shape}"
        )

    # GluonTS: (D, T)
    # Darts:   (T, D)
    values = target.T

    times = pd.date_range(
        start=start,
        periods=values.shape[0],
        freq=freq
    )

    columns = [
        f"node_{i}"
        for i in range(values.shape[1])
    ]

    return TimeSeries.from_times_and_values(
        times,
        values,
        columns=columns
    )


train_grouper = MultivariateGrouper(
    max_target_dim=target_dim
)

test_grouper = MultivariateGrouper(
    num_test_dates=num_test_dates,
    max_target_dim=target_dim
)

train_mv_items = list(
    train_grouper(train_list)
)

test_mv_items = list(
    test_grouper(test_list)
)

train_ts = gluonts_item_to_darts_mv(
    train_mv_items[0],
    freq
)

test_ts_list = [
    gluonts_item_to_darts_mv(
        item,
        freq
    )
    for item in test_mv_items
]

print("Training shape:", train_ts.shape)
print("Test windows:", len(test_ts_list))

Training shape: (7009, 137, 1)
Test windows: 7

In [4]:
# ============================================================
# CELL 5 — SCALE TARGET
# ============================================================

y_scaler = Scaler()

train_y_sc = y_scaler.fit_transform(
    train_ts
).astype(np.float32)

print("Scaled training shape:", train_y_sc.shape)

Scaled training shape: (7009, 137, 1)

In [5]:
# ============================================================
# CELL 6 — CREATE TEST WINDOWS
# ============================================================

def get_test_windows(dataset, num_nodes):

    all_series = []

    for entry in dataset:

        idx = pd.date_range(
            start=entry["start"].to_timestamp(),
            periods=len(entry["target"]),
            freq=entry["start"].freqstr
        )

        all_series.append(
            pd.Series(
                entry["target"],
                index=idx
            )
        )

    num_windows = len(all_series) // num_nodes

    windows = []

    for w in range(num_windows):

        start_idx = w * num_nodes
        end_idx = (w + 1) * num_nodes

        window_df = pd.concat(
            all_series[start_idx:end_idx],
            axis=1
        )

        window_df.columns = [
            f"node_{i}"
            for i in range(num_nodes)
        ]

        windows.append(window_df)

    return windows


test_windows = get_test_windows(
    ds.test,
    num_nodes=target_dim
)

print("Number of test windows:", len(test_windows))

for i, window in enumerate(test_windows):
    print(
        f"Window {i+1}:",
        window.shape,
        window.index[0],
        "→",
        window.index[-1]
    )

Number of test windows: 7
Window 1: (7033, 137) 2006-01-01 00:00:00 → 2006-10-21 00:00:00
Window 2: (7057, 137) 2006-01-01 00:00:00 → 2006-10-22 00:00:00
Window 3: (7081, 137) 2006-01-01 00:00:00 → 2006-10-23 00:00:00
Window 4: (7105, 137) 2006-01-01 00:00:00 → 2006-10-24 00:00:00
Window 5: (7129, 137) 2006-01-01 00:00:00 → 2006-10-25 00:00:00
Window 6: (7153, 137) 2006-01-01 00:00:00 → 2006-10-26 00:00:00
Window 7: (7177, 137) 2006-01-01 00:00:00 → 2006-10-27 00:00:00

In [6]:
# ============================================================
# CELL 7 — METRICS
# ============================================================

def to_tensor(x):
    if isinstance(x, torch.Tensor):
        return x.float()
    return torch.as_tensor(
        x,
        dtype=torch.float32
    )


def point_forecast(y_pred, method="median"):

    y_pred = to_tensor(y_pred)

    if method == "mean":
        return torch.mean(y_pred, dim=-1)

    if method == "median":
        return torch.median(y_pred, dim=-1).values

    if isinstance(method, float):
        return torch.quantile(
            y_pred,
            method,
            dim=-1
        )

    raise ValueError(
        "point_method must be mean, median or quantile"
    )


def mae(y_true, y_pred):
    return torch.mean(
        torch.abs(
            to_tensor(y_true) -
            point_forecast(y_pred)
        )
    ).item()


def mse(y_true, y_pred):
    return torch.mean(
        (
            to_tensor(y_true) -
            point_forecast(y_pred)
        ) ** 2
    ).item()


def rmse(y_true, y_pred):
    return np.sqrt(
        mse(y_true, y_pred)
    )


def smape(y_true, y_pred, eps=1e-8):

    y_true = to_tensor(y_true)
    pred = point_forecast(y_pred)

    denominator = torch.clamp(
        (torch.abs(y_true) + torch.abs(pred)) / 2,
        min=eps
    )

    return torch.mean(
        torch.abs(y_true - pred) / denominator * 100
    ).item()


def mape(y_true, y_pred, eps=1e-8):

    y_true = to_tensor(y_true)
    pred = point_forecast(y_pred)

    denominator = torch.clamp(
        torch.abs(y_true),
        min=eps
    )

    return torch.mean(
        torch.abs(y_true - pred) /
        denominator * 100
    ).item()


def mpe(y_true, y_pred, eps=1e-8):

    y_true = to_tensor(y_true)
    pred = point_forecast(y_pred)

    denominator = torch.clamp(
        y_true,
        min=eps
    )

    return torch.mean(
        (y_true - pred) /
        denominator * 100
    ).item()


def smdape(y_true, y_pred, eps=1e-8):

    y_true = to_tensor(y_true)
    pred = point_forecast(y_pred)

    denominator = torch.clamp(
        (torch.abs(y_true) + torch.abs(pred)) / 2,
        min=eps
    )

    error = (
        torch.abs(y_true - pred) /
        denominator * 100
    )

    return torch.median(error).item()


def opl(y_true, y_pred):

    y_true = to_tensor(y_true)
    pred = point_forecast(y_pred)

    true_direction = torch.sign(
        y_true[1:] - y_true[:-1]
    )

    pred_direction = torch.sign(
        pred[1:] - y_true[:-1]
    )

    return torch.mean(
        torch.abs(
            true_direction -
            pred_direction
        ) / 2
    ).item()


def mase(y_true, y_pred, y_train):

    y_true = to_tensor(y_true)
    y_train = to_tensor(y_train)

    pred = point_forecast(y_pred)

    forecast_error = torch.abs(
        y_true - pred
    )

    scale = torch.mean(
        torch.abs(
            y_train[1:] -
            y_train[:-1]
        ),
        dim=0
    )

    scale = torch.clamp(
        scale,
        min=1e-8
    )

    return torch.mean(
        forecast_error /
        scale.unsqueeze(0)
    ).item()


def rmsse(y_true, y_pred, y_train):

    y_true = to_tensor(y_true)
    y_train = to_tensor(y_train)

    pred = point_forecast(y_pred)

    forecast_error = (
        y_true - pred
    ) ** 2

    scale = torch.mean(
        (
            y_train[1:] -
            y_train[:-1]
        ) ** 2,
        dim=0
    )

    scale = torch.clamp(
        scale,
        min=1e-8
    )

    return torch.mean(
        torch.sqrt(
            forecast_error /
            scale.unsqueeze(0)
        )
    ).item()


def crps(y_true, y_pred):

    y_true = to_tensor(y_true)
    y_pred = to_tensor(y_pred)

    y_true = y_true.unsqueeze(-1)

    term1 = torch.mean(
        torch.abs(
            y_pred - y_true
        ),
        dim=-1
    )

    pred_i = y_pred.unsqueeze(-1)
    pred_j = y_pred.unsqueeze(-2)

    term2 = torch.mean(
        torch.abs(pred_i - pred_j),
        dim=(-1, -2)
    )

    return torch.mean(
        term1 - 0.5 * term2
    ).item()


def picp(y_true, y_pred, alpha=0.05):

    y_true = to_tensor(y_true)
    y_pred = to_tensor(y_pred)

    lower = torch.quantile(
        y_pred,
        alpha / 2,
        dim=-1
    )

    upper = torch.quantile(
        y_pred,
        1 - alpha / 2,
        dim=-1
    )

    return torch.mean(
        (
            (y_true >= lower) &
            (y_true <= upper)
        ).float()
    ).item()


def mpiw(y_pred, alpha=0.05):

    y_pred = to_tensor(y_pred)

    lower = torch.quantile(
        y_pred,
        alpha / 2,
        dim=-1
    )

    upper = torch.quantile(
        y_pred,
        1 - alpha / 2,
        dim=-1
    )

    return torch.mean(
        upper - lower
    ).item()


def mis(y_true, y_pred, alpha=0.05):

    y_true = to_tensor(y_true)
    y_pred = to_tensor(y_pred)

    lower = torch.quantile(
        y_pred,
        alpha / 2,
        dim=-1
    )

    upper = torch.quantile(
        y_pred,
        1 - alpha / 2,
        dim=-1
    )

    width = upper - lower

    penalty_lower = (
        2 / alpha
    ) * torch.maximum(
        lower - y_true,
        torch.zeros_like(y_true)
    )

    penalty_upper = (
        2 / alpha
    ) * torch.maximum(
        y_true - upper,
        torch.zeros_like(y_true)
    )

    return torch.mean(
        width +
        penalty_lower +
        penalty_upper
    ).item()

In [7]:
# ============================================================
# CELL 8 — EVALUATION
# ============================================================

def evaluate_model(
    model,
    test_windows,
    y_scaler,
    pred_len=24,
    num_samples=100,
    seed=42,
):

    window_results = []
    total_inference_time = 0.0

    for window_idx, window_df in enumerate(test_windows):

        print(
            f"  Evaluating window "
            f"{window_idx + 1}/{len(test_windows)}..."
        )

        full_ts = TimeSeries.from_dataframe(
            window_df
        ).astype(np.float32)

        full_sc = y_scaler.transform(
            full_ts
        ).astype(np.float32)

        past_sc = full_sc[:-pred_len]
        future = full_ts[-pred_len:]

        # ----------------------------------------------------
        # Prediction
        # ----------------------------------------------------

        start = time.time()

        forecast_sc = model.predict(
            n=pred_len,
            series=past_sc,
            num_samples=num_samples,
            clip_preds=True,
            verbose=False,
            random_state=seed,
        )

        inference_time = time.time() - start
        total_inference_time += inference_time

        # ----------------------------------------------------
        # Back to original scale
        # ----------------------------------------------------

        forecast = y_scaler.inverse_transform(
            forecast_sc
        )

        assert forecast.time_index.equals(
            future.time_index
        ), f"Time mismatch in window {window_idx}"

        # Shape:
        # forecast -> (T, D, S)
        y_pred = forecast.all_values(
            copy=False
        )

        # Ground truth -> (T, D)
        y_true = future.all_values(
            copy=False
        ).squeeze(-1)

        # Training history for scaled metrics
        y_train = full_ts[:-pred_len].all_values(
            copy=False
        ).squeeze(-1)

        # ----------------------------------------------------
        # Metrics
        # ----------------------------------------------------

        metrics = {

            # Point
            "MAE": mae(y_true, y_pred),
            "MSE": mse(y_true, y_pred),
            "RMSE": rmse(y_true, y_pred),
            "MAPE": mape(y_true, y_pred),
            "sMAPE": smape(y_true, y_pred),
            "sMdAPE": smdape(y_true, y_pred),
            "MPE": mpe(y_true, y_pred),
            "OPL": opl(y_true, y_pred),

            # Scaled
            "MASE": mase(
                y_true,
                y_pred,
                y_train
            ),

            "RMSSE": rmsse(
                y_true,
                y_pred,
                y_train
            ),

            # Probabilistic
            "CRPS": crps(
                y_true,
                y_pred
            ),

            "PICP": picp(
                y_true,
                y_pred,
                alpha=0.05
            ),

            "MIS": mis(
                y_true,
                y_pred,
                alpha=0.05
            ),

            "MPIW": mpiw(
                y_pred,
                alpha=0.05
            ),

        }

        window_results.append(metrics)

    # --------------------------------------------------------
    # Average across all 7 windows
    # --------------------------------------------------------

    results_df = pd.DataFrame(
        window_results
    )

    summary = results_df.mean().to_frame(
        "Average_Score"
    )

    summary.loc[
        "Inference Time",
        "Average_Score"
    ] = (
        total_inference_time /
        len(test_windows)
    )

    return summary

In [9]:
# ============================================================
# CELL 9 — HEALTHY MODELS
# ============================================================

from engressionts.models.neuralforecast import (
    EnBiTCN,
    EniTransformer,
    EnKAN,
    EnMLP,
    EnMLPMultivariate,
    EnPatchTST,
    EnRMoK,
    EnSOFTS,
    EnSOFTSSharp,
    EnStemGNN,
    EnTimeXer,
    EnTSMixerx,
    EnXLinear,
)

MODELS_TO_RUN = [

    ("EnBiTCN", EnBiTCN),
    ("EniTransformer", EniTransformer),
    ("EnKAN", EnKAN),
    ("EnMLP", EnMLP),
    ("EnMLPMultivariate", EnMLPMultivariate),
    ("EnPatchTST", EnPatchTST),
    ("EnRMoK", EnRMoK),
    ("EnSOFTS", EnSOFTS),
    ("EnSOFTSSharp", EnSOFTSSharp),
    ("EnStemGNN", EnStemGNN),
    ("EnTimeXer", EnTimeXer),
    ("EnTSMixerx", EnTSMixerx),
    ("EnXLinear", EnXLinear),
]

print("Models to run:")

for name, _ in MODELS_TO_RUN:
    print(" -", name)

Models to run:
 - EnBiTCN
 - EniTransformer
 - EnKAN
 - EnMLP
 - EnMLPMultivariate
 - EnPatchTST
 - EnRMoK
 - EnSOFTS
 - EnSOFTSSharp
 - EnStemGNN
 - EnTimeXer
 - EnTSMixerx
 - EnXLinear

In [10]:
# ============================================================
# CELL 10 — MODELS NOT RUNNING IN THIS BENCHMARK
# ============================================================

# MEMORY-LIMITED
#
# EnAutoformer
# EnInformer
# EnTimesNet
# EnxLSTM
#
# Known configuration:
#
# batch_size = 8
# max_steps = 26130
#
# ------------------------------------------------------------
#
# NUMERICAL STABILITY TODO
#
# EnFEDformer
#
# Currently excluded because of the known NaN issue.
#
# ------------------------------------------------------------
#
# NOT A STANDARD MODEL FOR THIS BENCHMARK
#
# EnHINT
#
# Wrapper / hierarchical model.
# Not applicable to this flat Solar benchmark.
#
# ------------------------------------------------------------
#
# REMOVED
#
# EnDeepAR
# EnDeepNPTS
# EnVanillaTransformer
#
# ------------------------------------------------------------

print("Heavy / TODO models are intentionally excluded.")

Heavy / TODO models are intentionally excluded.

In [10]:
# ============================================================
# CELL 11 — TRAIN + EVALUATE ALL MODELS
# ============================================================

from engressionts.models.darts.en_nf_model import (
    EngressionNeuralForecastModel
)

all_results = []

for model_idx, (model_name, model_cls) in enumerate(
    MODELS_TO_RUN,
    start=1
):

    print("\n")
    print("=" * 70)
    print(
        f"[{model_idx}/{len(MODELS_TO_RUN)}] "
        f"{model_name}"
    )
    print("=" * 70)

    # --------------------------------------------------------
    # Clean memory
    # --------------------------------------------------------

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # --------------------------------------------------------
    # Create model
    # --------------------------------------------------------

    model = EngressionNeuralForecastModel(

        input_chunk_length=INPUT_CHUNK_LENGTH,

        output_chunk_length=OUTPUT_CHUNK_LENGTH,

        model=model_cls,

        batch_size=BATCH_SIZE,

        model_kwargs={
            "num_samples_train": NUM_SAMPLES_TRAIN,
            "noise_std": NOISE_STD,
            "noise_type": NOISE_TYPE,
        },

        random_state=SEED,

        optimizer_kwargs={
            "lr": LEARNING_RATE
        },

        pl_trainer_kwargs={
            "accelerator": "gpu",
            "devices": [0],
            "max_steps": MAX_STEPS,
        },
    )

    # --------------------------------------------------------
    # Train
    # --------------------------------------------------------

    print("\nTraining...")

    start = time.time()

    try:

        model.fit(
            series=train_y_sc,
            verbose=True,
        )

        training_time = time.time() - start

        print(
            f"\nTraining time: "
            f"{training_time:.2f} seconds"
        )

    except Exception as e:

        print(
            f"\n❌ {model_name} FAILED DURING TRAINING"
        )

        print(
            type(e).__name__,
            ":",
            e
        )

        continue

    # --------------------------------------------------------
    # Evaluate
    # --------------------------------------------------------

    print("\nEvaluating 7 test windows...")

    try:

        metrics = evaluate_model(
            model=model,
            test_windows=test_windows,
            y_scaler=y_scaler,
            pred_len=OUTPUT_CHUNK_LENGTH,
            num_samples=NUM_SAMPLES_PRED,
            seed=SEED,
        )

        print("\nResults:")
        display(metrics)

    except Exception as e:

        print(
            f"\n❌ {model_name} FAILED DURING EVALUATION"
        )

        print(
            type(e).__name__,
            ":",
            e
        )

        continue

    # --------------------------------------------------------
    # Save one row
    # --------------------------------------------------------

    row = {
        "Model": model_name,

        "Batch Size": BATCH_SIZE,

        "Max Steps": MAX_STEPS,

        "Training Samples": NUM_SAMPLES_TRAIN,

        "Prediction Samples": NUM_SAMPLES_PRED,

        "Noise Std": NOISE_STD,

        "Noise Type": NOISE_TYPE,

        "Input Length": INPUT_CHUNK_LENGTH,

        "Forecast Horizon": OUTPUT_CHUNK_LENGTH,

        "Training Time (s)": training_time,

    }

    for metric_name in metrics.index:

        row[metric_name] = metrics.loc[
            metric_name,
            "Average_Score"
        ]

    all_results.append(row)

    # --------------------------------------------------------
    # Save after EVERY model
    # --------------------------------------------------------

    results_df = pd.DataFrame(
        all_results
    )

    results_df.to_csv(
        RESULTS_FILE,
        index=False
    )

    print(
        f"\n✓ Saved results to {RESULTS_FILE}"
    )

    # --------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------

    del model

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True

======================================================================
[1/13] EnBiTCN
======================================================================

Training...

INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.utilities.rank_zero:You are using a CUDA device ('NVIDIA GeForce RTX 3050 6GB Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnBiTCN          | 6.2 K  | train
-------------------------------------------------------------
6.2 K     Trainable params
5         Non-trainable params
6.2 K     Total params
0.025     Total estimated model params size (MB)
41        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 15.96 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              2.768544e+01
MSE              1.743418e+03
RMSE             3.956999e+01
MAPE             9.169232e+10
sMAPE            1.369206e+02
sMdAPE           1.856184e+02
MPE             -9.169232e+10
OPL              4.154237e-01
MASE             2.200044e+00
RMSSE            1.298013e+00
CRPS             2.201325e+01
PICP             6.129215e-01
MIS              4.319878e+02
MPIW             4.768698e+01
Inference Time   9.166397e-02

✓ Saved results to nf_solar_results.csv


======================================================================
[2/13] EniTransformer
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EniTransformer   | 6.3 M  | train
-------------------------------------------------------------
6.3 M     Trainable params
5         Non-trainable params
6.3 M     Total params
25.324    Total estimated model params size (MB)
47        Modules in train mode
0         Modules in eval mode

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.

Training time: 48.80 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Results:

                Average_Score
MAE              1.857381e+01
MSE              1.068204e+03
RMSE             3.137502e+01
MAPE             2.854218e+10
sMAPE            9.105908e+01
sMdAPE           6.769187e+01
MPE             -2.854218e+10
OPL              2.963912e-01
MASE             1.456538e+00
RMSSE            8.586312e-01
CRPS             1.426487e+01
PICP             8.671359e-01
MIS              1.999308e+02
MPIW             6.473387e+01
Inference Time   9.686412e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[3/13] EnKAN
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42

Training...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnKAN            | 245 K  | train
-------------------------------------------------------------
245 K     Trainable params
5         Non-trainable params
245 K     Total params
0.983     Total estimated model params size (MB)
19        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.

Training time: 63.46 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Results:

                Average_Score
MAE              1.993769e+01
MSE              1.231707e+03
RMSE             3.288741e+01
MAPE             3.466427e+10
sMAPE            1.245390e+02
sMdAPE           1.389983e+02
MPE             -3.466427e+10
OPL              3.864533e-01
MASE             1.584593e+00
RMSSE            9.346393e-01
CRPS             1.443960e+01
PICP             9.224018e-01
MIS              1.710479e+02
MPIW             6.859313e+01
Inference Time   1.148329e+00

✓ Saved results to nf_solar_results.csv


======================================================================
[4/13] EnMLP
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42

Training...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnMLP            | 1.1 M  | train
-------------------------------------------------------------
1.1 M     Trainable params
5         Non-trainable params
1.1 M     Total params
4.399     Total estimated model params size (MB)
18        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 14.36 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.775515e+01
MSE              1.305347e+03
RMSE             3.326490e+01
MAPE             1.078987e+10
sMAPE            9.584593e+01
sMdAPE           9.600035e+01
MPE             -1.078987e+10
OPL              3.054586e-01
MASE             1.407635e+00
RMSSE            8.299193e-01
CRPS             1.300695e+01
PICP             9.384341e-01
MIS              1.439902e+02
MPIW             7.515457e+01
Inference Time   1.329413e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[5/13] EnMLPMultivariate
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training...

INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type              | Params | Mode
--------------------------------------------------------------
0 | criterion       | MSELoss           | 0      | train
1 | train_criterion | MSELoss           | 0      | train
2 | val_criterion   | MSELoss           | 0      | train
3 | train_metrics   | MetricCollection  | 0      | train
4 | val_metrics     | MetricCollection  | 0      | train
5 | nf              | EnMLPMultivariate | 7.8 M  | train
--------------------------------------------------------------
7.8 M     Trainable params
5         Non-trainable params
7.8 M     Total params
31.151    Total estimated model params size (MB)
18        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 3.26 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.661289e+01
MSE              1.039089e+03
RMSE             2.971503e+01
MAPE             1.132213e+10
sMAPE            9.580542e+01
sMdAPE           7.052993e+01
MPE             -1.132213e+10
OPL              2.929002e-01
MASE             1.309367e+00
RMSSE            7.716608e-01
CRPS             1.308085e+01
PICP             7.429614e-01
MIS              2.389465e+02
MPIW             3.307727e+01
Inference Time   1.312201e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[6/13] EnPatchTST
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnPatchTST       | 409 K  | train
-------------------------------------------------------------
409 K     Trainable params
8         Non-trainable params
409 K     Total params
1.637     Total estimated model params size (MB)
101       Modules in train mode
0         Modules in eval mode

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.

Training time: 83.72 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Results:

                Average_Score
MAE              1.911418e+01
MSE              1.308730e+03
RMSE             3.360900e+01
MAPE             2.227372e+10
sMAPE            8.918387e+01
sMdAPE           6.288039e+01
MPE             -2.227372e+10
OPL              2.962098e-01
MASE             1.514176e+00
RMSSE            8.926686e-01
CRPS             1.478605e+01
PICP             9.285280e-01
MIS              1.707518e+02
MPIW             8.638651e+01
Inference Time   7.763229e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[7/13] EnRMoK
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42

Training...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnRMoK           | 9.1 K  | train
-------------------------------------------------------------
9.1 K     Trainable params
5         Non-trainable params
9.1 K     Total params
0.036     Total estimated model params size (MB)
25        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 20.06 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              2.071500e+01
MSE              1.336124e+03
RMSE             3.420339e+01
MAPE             3.704255e+10
sMAPE            1.168719e+02
sMdAPE           1.328826e+02
MPE             -3.704255e+10
OPL              3.634674e-01
MASE             1.633817e+00
RMSSE            9.633443e-01
CRPS             1.542616e+01
PICP             9.281369e-01
MIS              1.806916e+02
MPIW             8.214986e+01
Inference Time   1.085209e-01

✓ Saved results to nf_solar_results.csv

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnSOFTS          | 6.9 M  | train
-------------------------------------------------------------
6.9 M     Trainable params
5         Non-trainable params
6.9 M     Total params
27.417    Total estimated model params size (MB)
42        Modules in train mode
0         Modules in eval mode

======================================================================
[8/13] EnSOFTS
======================================================================

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 47.72 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.715002e+01
MSE              9.404840e+02
RMSE             2.988142e+01
MAPE             2.069330e+10
sMAPE            7.947140e+01
sMdAPE           5.456509e+01
MPE             -2.069330e+10
OPL              2.547264e-01
MASE             1.344960e+00
RMSSE            7.927622e-01
CRPS             1.320368e+01
PICP             8.673966e-01
MIS              1.653690e+02
MPIW             6.329004e+01
Inference Time   1.961304e-01

✓ Saved results to nf_solar_results.csv

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnSOFTSSharp     | 6.9 M  | train
-------------------------------------------------------------
6.9 M     Trainable params
5         Non-trainable params
6.9 M     Total params
27.417    Total estimated model params size (MB)
50        Modules in train mode
0         Modules in eval mode

======================================================================
[9/13] EnSOFTSSharp
======================================================================

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 46.59 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.698211e+01
MSE              9.653914e+02
RMSE             3.012976e+01
MAPE             1.563766e+10
sMAPE            6.832308e+01
sMdAPE           4.172132e+01
MPE             -1.563766e+10
OPL              2.466337e-01
MASE             1.336075e+00
RMSSE            7.876483e-01
CRPS             1.317988e+01
PICP             8.641814e-01
MIS              1.727707e+02
MPIW             6.238892e+01
Inference Time   3.099358e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[10/13] EnStemGNN
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training...

INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnStemGNN        | 4.3 M  | train
-------------------------------------------------------------
4.3 M     Trainable params
5         Non-trainable params
4.3 M     Total params
17.157    Total estimated model params size (MB)
71        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 43.15 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              2.094895e+01
MSE              1.313391e+03
RMSE             3.560353e+01
MAPE             3.224241e+10
sMAPE            9.382761e+01
sMdAPE           6.986790e+01
MPE             -3.224241e+10
OPL              3.285352e-01
MASE             1.668816e+00
RMSSE            9.845208e-01
CRPS             1.807633e+01
PICP             5.556135e-01
MIS              4.841450e+02
MPIW             2.530304e+01
Inference Time   1.960022e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[11/13] EnTimeXer
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training...

INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnTimeXer        | 8.5 M  | train
-------------------------------------------------------------
8.5 M     Trainable params
5         Non-trainable params
8.5 M     Total params
34.099    Total estimated model params size (MB)
70        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 175.40 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.662969e+01
MSE              9.099028e+02
RMSE             2.953055e+01
MAPE             1.388065e+10
sMAPE            6.684732e+01
sMdAPE           3.952772e+01
MPE             -1.388065e+10
OPL              2.296096e-01
MASE             1.310283e+00
RMSSE            7.727100e-01
CRPS             1.286555e+01
PICP             8.713504e-01
MIS              1.673597e+02
MPIW             6.162778e+01
Inference Time   6.405257e-01

✓ Saved results to nf_solar_results.csv


======================================================================
[12/13] EnTSMixerx
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnTSMixerx       | 79.9 K | train
-------------------------------------------------------------
79.9 K    Trainable params
5         Non-trainable params
79.9 K    Total params
0.319     Total estimated model params size (MB)
58        Modules in train mode
0         Modules in eval mode

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 4.32 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...
  Evaluating window 7/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Results:

                Average_Score
MAE              1.625398e+01
MSE              9.084244e+02
RMSE             2.949275e+01
MAPE             1.211702e+10
sMAPE            5.834074e+01
sMdAPE           2.098170e+01
MPE             -1.211702e+10
OPL              2.189328e-01
MASE             1.279355e+00
RMSSE            7.541271e-01
CRPS             1.232455e+01
PICP             8.783889e-01
MIS              1.444997e+02
MPIW             6.143224e+01
Inference Time   8.424933e-02

✓ Saved results to nf_solar_results.csv


======================================================================
[13/13] EnXLinear
======================================================================

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name            | Type             | Params | Mode
-------------------------------------------------------------
0 | criterion       | MSELoss          | 0      | train
1 | train_criterion | MSELoss          | 0      | train
2 | val_criterion   | MSELoss          | 0      | train
3 | train_metrics   | MetricCollection | 0      | train
4 | val_metrics     | MetricCollection | 0      | train
5 | nf              | EnXLinear        | 163 K  | train
-------------------------------------------------------------
163 K     Trainable params
5         Non-trainable params
163 K     Total params
0.653     Total estimated model params size (MB)
34        Modules in train mode
0         Modules in eval mode

Training...

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=109` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Training time: 7.69 seconds

Evaluating 7 test windows...
  Evaluating window 1/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 2/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 3/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 4/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 5/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 6/7...

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  Evaluating window 7/7...

Results:

                Average_Score
MAE              1.868204e+01
MSE              1.259299e+03
RMSE             3.311875e+01
MAPE             2.101238e+10
sMAPE            8.821531e+01
sMdAPE           5.981172e+01
MPE             -2.101238e+10
OPL              2.977740e-01
MASE             1.475442e+00
RMSSE            8.700156e-01
CRPS             1.432848e+01
PICP             9.426920e-01
MIS              1.484246e+02
MPIW             9.083882e+01
Inference Time   1.057697e-01

✓ Saved results to nf_solar_results.csv

In [ ]:
# ============================================================
# CELL 12 — FINAL RESULTS
# ============================================================

if len(all_results) == 0:

    print(
        "No models completed successfully."
    )

else:

    final_results = pd.DataFrame(
        all_results
    )

    print("=" * 70)
    print("FINAL NF ENGRESSION RESULTS")
    print("=" * 70)

    display(
        final_results
    )

    final_results.to_csv(
        RESULTS_FILE,
        index=False
    )

    print(
        f"\nSaved to: {RESULTS_FILE}"
    )

======================================================================
FINAL NF ENGRESSION RESULTS
======================================================================

,Model,Batch Size,Max Steps,Training Samples,Prediction Samples,Noise Std,Noise Type,Input Length,Forecast Horizon,Training Time (s),...,sMdAPE,MPE,OPL,MASE,RMSSE,CRPS,PICP,MIS,MPIW,Inference Time
0,EnBiTCN,64,109,2,100,1.0,uniform,24,24,15.964740,...,185.618353,-9.169232e+10,0.415424,2.200044,1.298013,22.013250,0.612921,431.987849,47.686978,0.091664
1,EniTransformer,64,109,2,100,1.0,uniform,24,24,48.798908,...,67.691872,-2.854218e+10,0.296391,1.456538,0.858631,14.264869,0.867136,199.930835,64.733867,0.968641
2,EnKAN,64,109,2,100,1.0,uniform,24,24,63.455391,...,138.998268,-3.466427e+10,0.386453,1.584593,0.934639,14.439596,0.922402,171.047873,68.593126,1.148329
3,EnMLP,64,109,2,100,1.0,uniform,24,24,14.363990,...,96.000349,-1.078987e+10,0.305459,1.407635,0.829919,13.006954,0.938434,143.990223,75.154567,0.132941
4,EnMLPMultivariate,64,109,2,100,1.0,uniform,24,24,3.263511,...,70.529932,-1.132213e+10,0.292900,1.309367,0.771661,13.080855,0.742961,238.946469,33.077266,0.131220
5,EnPatchTST,64,109,2,100,1.0,uniform,24,24,83.720216,...,62.880388,-2.227372e+10,0.296210,1.514176,0.892669,14.786047,0.928528,170.751835,86.386512,0.776323
6,EnRMoK,64,109,2,100,1.0,uniform,24,24,20.057209,...,132.882627,-3.704255e+10,0.363467,1.633817,0.963344,15.426163,0.928137,180.691644,82.149858,0.108521
7,EnSOFTS,64,109,2,100,1.0,uniform,24,24,47.715155,...,54.565085,-2.069330e+10,0.254726,1.344960,0.792762,13.203680,0.867397,165.369020,63.290043,0.196130
8,EnSOFTSSharp,64,109,2,100,1.0,uniform,24,24,46.587390,...,41.721324,-1.563766e+10,0.246634,1.336075,0.787648,13.179879,0.864181,172.770691,62.388918,0.309936
9,EnStemGNN,64,109,2,100,1.0,uniform,24,24,43.152930,...,69.867896,-3.224241e+10,0.328535,1.668816,0.984521,18.076334,0.555613,484.145011,25.303036,0.196002
10,EnTimeXer,64,109,2,100,1.0,uniform,24,24,175.395579,...,39.527718,-1.388065e+10,0.229610,1.310283,0.772710,12.865547,0.871350,167.359704,61.627777,0.640526
11,EnTSMixerx,64,109,2,100,1.0,uniform,24,24,4.321104,...,20.981704,-1.211702e+10,0.218933,1.279355,0.754127,12.324549,0.878389,144.499698,61.432245,0.084249
12,EnXLinear,64,109,2,100,1.0,uniform,24,24,7.687340,...,59.811724,-2.101238e+10,0.297774,1.475442,0.870016,14.328478,0.942692,148.424642,90.838825,0.105770

Saved to: nf_solar_results.csv

: